[2024-04-10T13:42:24.891+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 21120051.2112 manual__2024-04-10T13:42:12.794307+00:00 [queued]>
[2024-04-10T13:42:24.907+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 21120051.2112 manual__2024-04-10T13:42:12.794307+00:00 [queued]>
[2024-04-10T13:42:24.909+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-10T13:42:24.937+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): 2112> on 2024-04-10 13:42:12.794307+00:00
[2024-04-10T13:42:24.950+0000] {standard_task_runner.py:60} INFO - Started process 115 to run task
[2024-04-10T13:42:24.974+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '21120051', '2112', 'manual__2024-04-10T13:42:12.794307+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpj3snycgf']
[2024-04-10T13:42:24.992+0000] {standard_task_runner.py:88} INFO - Job 10: Subtask 2112
[2024-04-10T13:42:25.581+0000] {task_command.py:423} INFO - Running <TaskInstance: 21120051.2112 manual__2024-04-10T13:42:12.794307+00:00 [running]> on host c34bafd0ff75
[2024-04-10T13:42:25.693+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='21120051' AIRFLOW_CTX_DAG_ID='21120051' AIRFLOW_CTX_TASK_ID='2112' AIRFLOW_CTX_EXECUTION_DATE='2024-04-10T13:42:12.794307+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-10T13:42:12.794307+00:00'
[2024-04-10T13:42:26.088+0000] {python.py:202} INFO - Done. Returned value was: {'status': 'error', 'message': 'Unexpected Response: 400 (Bad Request)\nRaw response content:\nb\'{"status":{"error":"Wrong input: Collection `21120051` already exists!"},"time":0.193855893}\''}
[2024-04-10T13:42:26.126+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=21120051, task_id=2112, execution_date=20240410T134212, start_date=20240410T134224, end_date=20240410T134226
[2024-04-10T13:42:26.220+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-10T13:42:26.599+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
