[2024-04-09T07:00:26.548+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 21120051.1200 manual__2024-04-09T07:00:11.764629+00:00 [queued]>
[2024-04-09T07:00:26.558+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 21120051.1200 manual__2024-04-09T07:00:11.764629+00:00 [queued]>
[2024-04-09T07:00:26.559+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-09T07:00:26.575+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): 1200> on 2024-04-09 07:00:11.764629+00:00
[2024-04-09T07:00:26.585+0000] {standard_task_runner.py:60} INFO - Started process 1238 to run task
[2024-04-09T07:00:26.591+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '21120051', '1200', 'manual__2024-04-09T07:00:11.764629+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpwn1inlxv']
[2024-04-09T07:00:26.595+0000] {standard_task_runner.py:88} INFO - Job 86: Subtask 1200
[2024-04-09T07:00:26.873+0000] {task_command.py:423} INFO - Running <TaskInstance: 21120051.1200 manual__2024-04-09T07:00:11.764629+00:00 [running]> on host a1b04a9393da
[2024-04-09T07:00:26.945+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='21120051' AIRFLOW_CTX_DAG_ID='21120051' AIRFLOW_CTX_TASK_ID='1200' AIRFLOW_CTX_EXECUTION_DATE='2024-04-09T07:00:11.764629+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-09T07:00:11.764629+00:00'
[2024-04-09T07:00:27.018+0000] {python.py:202} INFO - Done. Returned value was: {'status': 'error', 'message': "2 validation errors for PointStruct\nvector.list[float]\n  Input should be a valid list [type=list_type, input_value='[0.012602259404957294, 0..., 0.057063158601522446]', input_type=str]\n    For further information visit https://errors.pydantic.dev/2.6/v/list_type\nvector.dict[str,union[list[float],SparseVector]]\n  Input should be a valid dictionary [type=dict_type, input_value='[0.012602259404957294, 0..., 0.057063158601522446]', input_type=str]\n    For further information visit https://errors.pydantic.dev/2.6/v/dict_type"}
[2024-04-09T07:00:27.040+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=21120051, task_id=1200, execution_date=20240409T070011, start_date=20240409T070026, end_date=20240409T070027
[2024-04-09T07:00:27.083+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-09T07:00:27.283+0000] {taskinstance.py:3309} INFO - 1 downstream tasks scheduled from follow-on schedule check
