[2024-04-09T10:32:32.279+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: 21120051.1200 scheduled__2024-04-09T10:27:19.350715+00:00 [queued]>
[2024-04-09T10:32:32.286+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: 21120051.1200 scheduled__2024-04-09T10:27:19.350715+00:00 [queued]>
[2024-04-09T10:32:32.287+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 2
[2024-04-09T10:32:32.418+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): 1200> on 2024-04-09 10:27:19.350715+00:00
[2024-04-09T10:32:32.424+0000] {standard_task_runner.py:60} INFO - Started process 2190 to run task
[2024-04-09T10:32:32.428+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', '21120051', '1200', 'scheduled__2024-04-09T10:27:19.350715+00:00', '--job-id', '164', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpiry4fpr9']
[2024-04-09T10:32:32.430+0000] {standard_task_runner.py:88} INFO - Job 164: Subtask 1200
[2024-04-09T10:32:32.471+0000] {task_command.py:423} INFO - Running <TaskInstance: 21120051.1200 scheduled__2024-04-09T10:27:19.350715+00:00 [running]> on host 602b1f5953a0
[2024-04-09T10:32:32.536+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='21120051' AIRFLOW_CTX_DAG_ID='21120051' AIRFLOW_CTX_TASK_ID='1200' AIRFLOW_CTX_EXECUTION_DATE='2024-04-09T10:27:19.350715+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-04-09T10:27:19.350715+00:00'
[2024-04-09T10:32:32.699+0000] {python.py:202} INFO - Done. Returned value was: {'status': 'success', 'message': 'Data inserted to Vector DB successfully', 'data': Database(MongoClient(host=['mongodb:27017'], document_class=dict, tz_aware=False, connect=True), 'midterm')}
[2024-04-09T10:32:32.705+0000] {xcom.py:664} ERROR - Object of type Database is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2024-04-09T10:32:32.707+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/serialization/serde.py", line 160, in serialize
    data = getattr(o, "serialize")()
  File "/home/airflow/.local/lib/python3.8/site-packages/pymongo/collection.py", line 3501, in __call__
    raise TypeError(
TypeError: 'Collection' object is not callable. If you meant to call the 'serialize' method on a 'Database' object it is failing because no such method exists.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 451, in _execute_task
    task_instance.xcom_push(key=XCOM_RETURN_KEY, value=xcom_value, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 3010, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 247, in set
    value = cls.serialize_value(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 662, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 93, in default
    return super().default(o)
  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Database is not JSON serializable
[2024-04-09T10:32:32.714+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=21120051, task_id=1200, execution_date=20240409T102719, start_date=20240409T103232, end_date=20240409T103232
[2024-04-09T10:32:32.726+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 164 for task 1200 (Object of type Database is not JSON serializable; 2190)
[2024-04-09T10:32:32.760+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-09T10:32:32.792+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
